version: "3.8"

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carrental_db
    volumes:
      - carrental_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  carrental_db:
